version: '3'
services:
  rating:
    image: 'com.thoughtworks/rating'
    ports:
      - "8081:8081"
    networks:
      - rating
    depends_on:
      - rating-postgres
    links:
      - rating-postgres
  rating-postgres:
    image: 'postgres'
    environment:
      - POSTGRES_PASSWORD=docker
      - POSTGRES_USER=postgres
      - POSTGRES_DB=rating
    expose:
      - 5432
    ports:
      - 5432:5432
    networks:
      - rating
networks:
  rating:
    driver: bridge

